version: "3.9"
services:
  postgres:
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      